[build]
  # Install dependencies in the functions directory
  command = "cd netlify/functions && npm install"
  # The directory that contains the publishable static files
  publish = "."
  # The directory that contains Netlify Functions
  functions = "netlify/functions"

[build.environment]
  # Set Node.js version
  NODE_VERSION = "18"
  # Install dependencies in the functions directory
  NPM_FLAGS = "--prefix=netlify/functions"

[functions]
  # Use esbuild for bundling
  node_bundler = "esbuild"
  # Mark these modules as external (they'll be available in the Lambda environment)
  external_node_modules = ["openai", "node-fetch", "form-data"]
  # Include all JS files in the functions directory
  included_files = ["netlify/functions/*.js"]
  # Set the Node.js version for functions
  node_version = "18"

# Global CORS headers
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Function-specific CORS headers
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Max-Age = "600"  # Cache preflight response for 10 minutes

# Redirect all requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
