[build]
  publish = "."
  command = "cd netlify/functions && npm install"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["formidable"]

# Handle CORS for API requests
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
