[build]
  command = "cd netlify/functions && npm install"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["openai", "node-fetch", "form-data"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
