[build]
publish = "."
command = "npm install --prefix netlify/functions"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"
NODE_OPTIONS = "--max_old_space_size=4096"

[functions]
node_bundler = "esbuild"
external_node_modules = []
included_files = ["netlify/functions/*.js"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/.netlify/functions/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization"
