[build]
  publish = "."
  command = ""  # No build command needed for static site

# Proxy all /api/* requests to Render backend
[[redirects]]
  from = "/api/*"
  to = "https://cole-ocr-llama.onrender.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Handle SPA routing - redirect all other paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
